Last login: Tue Aug  6 14:11:49 on ttys000
(base) meennutjira@macbook-2 ~ % cd /Users/meennutjira/Documents/Streamlit_Intern_Project
(base) meennutjira@macbook-2 Streamlit_Intern_Project % mkdir .streamlit

mkdir: .streamlit: File exists
(base) meennutjira@macbook-2 Streamlit_Intern_Project % nano .streamlit/secrets.toml
















  GNU nano 2.0.6         File: .streamlit/secrets.toml                Modified  

[gcp_service_account]
type = "service_account"
project_id = "intern-streamlit-project"
private_key_id = "b022165a3f58a1a43cb2e87fa449450045143806"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKY$
client_email = "intern-streamlit-project-servi@intern-streamlit-project.iam.gse$
client_id  "103519999538728952119"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inter$









^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Page ^K Cut Text  ^C Cur Pos
^X Exit      ^J Justify   ^W Where Is  ^V Next Page ^U UnCut Text^T To Spell
