[gcp_service_account]
type = "service_account"
project_id = "intern-streamlit-project"
private_key_id = "b022165a3f58a1a43cb2e87fa449450045143806"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKY$
client_email = "intern-streamlit-project-servi@intern-streamlit-project.iam.gse$
client_id  "103519999538728952119"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/inter$
